### PR TITLE
Update `stylelint-config-recommended` to 5.0

### PR DESCRIPTION
**Pull request by tysongach**
Changelog: https://github.com/stylelint/stylelint-config-recommended/blob/master/CHANGELOG.md#500

I’ve also run `npm audit fix` in a separate commit to fix 7 vulnerabilities.

### CODE REVIEW

**Comment by tysongach** [comment]
@kristerkari 👋 Hello! Any chance of a review on this? Thanks.

**Comment by fgblomqvist** [comment]
You also have to disable `no-invalid-position-at-import-rule` when updating, because it was turned on in 5.0.0.
See:
https://github.com/stylelint/stylelint/issues/5322

Otherwise you will have a non-working lint config.

**Comment by kristerkari** [comment]
Alright, I'll create a new PR that both updates `stylelint-config-recommended` and disables `no-invalid-position-at-import-rule` rule.

**Comment by tysongach** [comment]
Thanks @kristerkari!

**Comment by kristerkari** [comment]
Thanks for the contribution @tysongach !

**Pull request closed without merging**
