### PR TITLE
Switch to GitHub Actions CI.

### PR DESCRIPTION
**Pull request by XhmikosR**
This is just a basic setup, I haven't backported the branch limitations.

@kristerkari: first you will need to enable GH Actions: https://github.com/features/actions

EDIT: it seems there's a bug and on Windows they use Node.js 8.10.0 which doesn't have `npm ci` command. https://github.com/actions/setup-node/issues/27

### CODE REVIEW

**Comment by XhmikosR** [comment]
@kristerkari what's your take on this?

**Comment by XhmikosR** [comment]
You can see this on my fork https://github.com/XhmikosR/stylelint-config-recommended-scss/commit/6eee6b7c2761e75c9d01dfb2c57fd6a17a786823/checks?check_suite_id=245911495

**Comment by kristerkari** [comment]
I haven't used Github's CI before, so I think that I need to look into it a bit before switching to use it.

If it has the same features as the other CI systems, then it's ok for me.

**Comment by XhmikosR** [comment]
It's actually better IMO so far. You can test fast, cross-platform, and without another 3rd-party service.

It does lack some features like caching, but those will be fixed eventually.

**Comment by ntwb** [comment]
stylelint switched a couple of weeks ago, pretty happy with it

You can see the final PR we merged adding them here:

https://github.com/stylelint/stylelint/pull/4285

**Comment by kristerkari** [comment]
Thanks for taking the time to do the changes!

**Comment by XhmikosR** [comment]
@kristerkari you haven't registered for Actions yet :/

**Comment by kristerkari** [comment]
I just did a few minutes ago

**Comment by XhmikosR** [comment]
Weird, I don't see them enabled yet...

**Comment by XhmikosR** [comment]
Either way, you should remove Travis and AppVeyor from apps/integrations/hooks when Actions is enabled.

**Comment by kristerkari** [comment]
I'm currently removing AppVeoyr and Travis

**Comment by kristerkari** [comment]
> Weird, I don't see them enabled yet...

It seems that there is some kind of a waiting list since it's a Beta feature. I guess we'll just have to wait a bit for it to be enabled.

**Comment by XhmikosR** [comment]
No worries, you can revert this and make a new PR to merge when it's enabled.

**Comment by kristerkari** [comment]
Let's see how long it takes, if it's quick, then I don't think that there is any need to revert the changes.

**Pull request merged**
