### PR TITLE
Update devDependencies.

### PR DESCRIPTION
**Pull request by XhmikosR**
@kristerkari mostly to test GH Actions.

Did you enable [automated security fixes](https://help.github.com/en/articles/configuring-automated-security-fixes) for your repos?

You could also add dependabot which is now owned by GitHub for normal dep updates too. The security fixes are independent of this.

My guess is this will fire when you merge it.

### CODE REVIEW

**Comment by XhmikosR** [comment]
@kristerkari friendly ping to see if this works for you :) Also, see my comments above

**Comment by kristerkari** [comment]
I've enabled the automated security fixes now. The actions are also now enabled, but I don't see any CI for this PR. Maybe it would work with a new PR?

**Comment by XhmikosR** [comment]
It will work after you merge it. This is for security reasons

**Comment by XhmikosR** [comment]
Maybe you need to push a patch your self. In every other project I did this, it worked fine after the PR was merged.

**Comment by kristerkari** [comment]
@XhmikosR I think that it was not working because after signing up for the Actions beta I needed to press one more opt-in button to enable Actions.

**Comment by XhmikosR** [comment]
@kristerkari oh, cool then. Next time you push something you should seem them firing hopefully.

**Pull request merged**
