### PR TITLE
Update devDependencies and add stylelint 13.0.0

### PR DESCRIPTION
**Pull request by XhmikosR**
/CC @kristerkari

### CODE REVIEW

**Comment by ux-engineer** [comment]
Cool, when will this be merged?

**Comment by XhmikosR** [comment]
Be patient, it's not even been a day since I made the PR and @kristerkari probably hasn't had the time to review + release a new version.

**Comment by XhmikosR** [comment]
Also, @kristerkari maybe we should first finish the stylelint-scss updates and then I will update this PR.

**Comment by kristerkari** [comment]
Hmm.. yeah @XhmikosR I need to have some time to go through all the currently open PRs for `stylelint-scss`.

@ux-engineer for now you can just ignore the warning from this config. We will release new version soon to get rid of the peer dependency warning.

**Comment by XhmikosR** [comment]
@kristerkari can you have a look at this? I rebased it.

**Pull request merged**
