### PR TITLE
Update `stylelint-config-recommended` to 5.0

### PR DESCRIPTION
**Pull request by kristerkari**
Closes #67

### CODE REVIEW

**Comment by kellyselden** [comment]
Wouldn't bumping this breaking change make your package also a breaking change instead of a minor release?

**Comment by kristerkari** [comment]
Yeah, I should have probably used a major version number instead of a minor one. I did not really pay enough attention.

**Comment by kellyselden** [comment]
We noticed the minor version breaking our linting. Are you planning to revert or leave as-is?

**Comment by kristerkari** [comment]
hmm.. I mean I can try to revert the minor and release it as major version instead, but I'm not sure how to do that without messing things up.

**Pull request merged**
